### ISSUE TITLE
Wrong suburb

### ISSUE THREAD

**Issue by magneticimpulse** [google/open-location-code#382] opened 2020-03-04 00:05 UTC
Northside should not be in the address for 9PQ2+PX Dublin, County Dublin, Ireland. It should be "Finglas Village, Dublin 11, Ireland". In fact "Northside" and "Ballygall" should be removed from all of the addresses in Dublin suburbs.

**Comment by drinckes** [comment] 2020-03-04 07:09
I'll close as a duplicate of #381 .

**Closed by drinckes** 2020-03-04 07:09 UTC

**Comment by magneticimpulse** [comment] 2020-05-19 05:13
Nothing has been done to fix this issue. my address has now been incorrectly copied to every website when i enter my Eircode!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.

**Comment by magneticimpulse** [comment] 2020-05-19 05:16
Nothing has been done to fix this issue.ive raised this in google maps numerous times and its ignored. my address has now been incorrectly copied to every website when i enter my Eircode!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.
