### ISSUE TITLE
Wrong area and bus stop name 

### ISSUE THREAD

**Issue by magneticimpulse** [google/open-location-code#384] opened 2020-03-04 00:31 UTC
9C5M9PP3+M8 "Glasnevin" and "Northside" should not be in the address. This suburb is "Finglas East". Also the bus stop is mixed up in this plus code.

**Comment by drinckes** [comment] 2020-03-04 07:11
Address formatting is a duplicate of #381.

Plus codes are areas, not points, and the bus stop is within the plus code area.

**Closed by drinckes** 2020-03-04 07:11 UTC

**Comment by magneticimpulse** [comment] 2020-03-05 20:19
hi i am not computer oriented. i dont know where the original source for the plus code comes from but it is incorrect. multiple times over 2 years i have contacted google maps to change it and they did not. i noticed a plus code attached with the incorrect address. plus code told me to come here to get it fixed. im not a computer person...i dont know how to rewrite the code. nobody will fix the surburb address where i live and the whole of the northside of Dublin addresses are wrong and google maps is based in Dublin and they cannot even get the address in their home city correct. what can i do to get the right person to fix it?

**Comment by magneticimpulse** [comment] 2020-05-19 05:16
Nothing has been done to fix this issue.ive raised this in google maps numerous times and its ignored. my address has now been incorrectly copied to every website when i enter my Eircode!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.

**Comment by magneticimpulse** [comment] 2020-05-19 05:20
Nothing has been done to fix this issue.ive raised this in google maps numerous times and its ignored. my address has now been incorrectly copied to every website when i enter my Eircode D11Y1E2!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.
