### ISSUE TITLE
Wrong suburb 

### ISSUE THREAD

**Issue by magneticimpulse** [google/open-location-code#383] opened 2020-03-04 00:25 UTC
9C5M9MRX+JJ should not have "Northside" in the address - none of this area is the Northside as it is not a suburb or Townland in any of Dublin. The address on the North Road suburb is "Finglas East, Dublin 11".

**Comment by drinckes** [comment] 2020-03-04 07:09
Closing as duplicate of #381.

**Closed by drinckes** 2020-03-04 07:09 UTC

**Comment by magneticimpulse** [comment] 2020-05-19 05:12
Nothing has been done to fix this issue. my address has now been incorrectly copied to every website when i enter my Eircode!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.

**Comment by magneticimpulse** [comment] 2020-05-19 05:17
Nothing has been done to fix this issue.ive raised this in google maps numerous times and its ignored. my address has now been incorrectly copied to every website when i enter my Eircode!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.

**Comment by magneticimpulse** [comment] 2020-05-19 05:20
Nothing has been done to fix this issue.ive raised this in google maps numerous times and its ignored. my address has now been incorrectly copied to every website when i enter my Eircode D11Y1E2!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.
