### ISSUE TITLE
Add pip package for python project

### ISSUE THREAD

**Issue by pokey** [google/open-location-code#137] opened 2018-02-23 14:35 UTC
It would be great if the python project were installable via pip.

**Comment by MarcusTheSmith** [comment] 2019-06-19 17:02
Has this been worked at all?

**Comment by zongweil** [comment] 2019-06-19 17:48
No, haven't gotten around to it. I'll try to take a look in the next couple weeks.

**Comment by virtadpt** [comment] 2019-07-17 23:53
Please do.  I just ran into this as a showstopper.

**Comment by zongweil** [comment] 2019-07-20 21:50
The python library is available on PyPi now: https://pypi.org/project/openlocationcode/

Please give it a try and let me know if you run into any issues.

**Comment by virtadpt** [comment] 2019-07-21 22:51
Local test passed.
Built, tested locally, and deployed.
It has to be referenced this way: `from openlocationcode import openlocationcode`

**Comment by zongweil** [comment] 2019-07-23 03:44
Thanks @virtadpt, changing the import fixed the test in #356. Closing this issue since the library is published and confirmed working!

**Closed by zongweil** 2019-07-23 03:44 UTC
