### ISSUE TITLE
Wrong suburb name and bus top area

### ISSUE THREAD

**Issue by magneticimpulse** [google/open-location-code#385] opened 2020-03-04 00:35 UTC
9C5M9PQ2+9PPlus. Overall 9C5M should have "Northside" removed from all of the Townlands/suburbs in Dublin. In this plus code, "Glasnevin" should also be removed. The suburb or townland address is "Finglas Village, Dublin 11".

**Comment by drinckes** [comment] 2020-03-04 07:12
Duplicate of #381.

**Closed by drinckes** 2020-03-04 07:12 UTC

**Comment by magneticimpulse** [comment] 2020-05-19 05:12
Nothing has been done to fix this issue. my address has now been incorrectly copied to every website when i enter my Eircode!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.

**Comment by magneticimpulse** [comment] 2020-05-19 05:16
Nothing has been done to fix this issue.ive raised this in google maps numerous times and its ignored. my address has now been incorrectly copied to every website when i enter my Eircode!! it comes up that i live in "Northside". what are ye lads doing? this is an absolute joke. you have no right to incorrectly put in my personal address on every website possible. why does every other area in dublin have the correct suburb! i will take you to court if you dont fix this today.
